type: telegram
name: telegram_default
log_level: info

token: "${CROWDSEC_TELEGRAM_TOKEN}"
chat_id: "${CROWDSEC_TELEGRAM_CHAT_ID}"

format: |
  {{range . -}}
  🚨 *CrowdSec Ban*
  *Scenario:* `{{.Scenario}}`
  *IP:* `{{.Source.IP}}` ({{.Source.Cn}})
  *Decisions:* {{.Decisions | len}}
  {{- end}}